import re
from typing import List, Dict, Any, Optional
import httpx
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound, VideoUnavailable
from app.models.schemas import TranscriptCue

class TranscriptService:
    def __init__(self):
        self.api = YouTubeTranscriptApi()

    @staticmethod
    def extract_video_id(url: str) -> Optional[str]:
        """Extract YouTube 11-char video ID from various URL patterns."""
        if not url:
            return None
        url = url.strip()
        # Direct video ID
        if re.match(r'^[a-zA-Z0-9_-]{11}$', url):
            return url
        
        patterns = [
            r'(?:v=|\/v\/|embed\/|shorts\/|youtu\.be\/|\/e\/)([a-zA-Z0-9_-]{11})',
            r'(?:[?&]v=)([a-zA-Z0-9_-]{11})',
            r'youtube\.com\/live\/([a-zA-Z0-9_-]{11})'
        ]
        for pattern in patterns:
            match = re.search(pattern, url)
            if match:
                return match.group(1)
        return None

    async def get_video_metadata(self, video_id: str) -> Dict[str, Any]:
        """Fetch video title and author using YouTube oEmbed endpoint (no API key required)."""
        oembed_url = f"https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v={video_id}&format=json"
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.get(oembed_url)
                if resp.status_code == 200:
                    data = resp.json()
                    return {
                        "title": data.get("title", f"YouTube Video ({video_id})"),
                        "author": data.get("author_name", "Unknown Author"),
                        "thumbnail_url": data.get("thumbnail_url", f"https://img.youtube.com/vi/{video_id}/maxresdefault.jpg")
                    }
        except Exception:
            pass
        
        return {
            "title": f"YouTube Video ({video_id})",
            "author": "YouTube Creator",
            "thumbnail_url": f"https://img.youtube.com/vi/{video_id}/hqdefault.jpg"
        }

    def fetch_transcript_cues(self, video_id: str) -> List[TranscriptCue]:
        """Fetch timestamped transcript cues for the video."""
        try:
            # 1. Try fetching directly
            fetched = self.api.fetch(video_id, languages=('en', 'en-US', 'en-GB'))
            raw_cues = fetched.to_raw_data()
        except Exception:
            # 2. Try listing available transcripts (e.g. autogenerated, other languages)
            try:
                transcript_list = self.api.list(video_id)
                # Try finding any English transcript
                t = None
                try:
                    t = transcript_list.find_transcript(['en', 'en-US', 'en-GB'])
                except Exception:
                    # Try finding generated transcript or any language and translate to en
                    available = list(transcript_list)
                    if available:
                        first_t = available[0]
                        if first_t.is_translatable:
                            t = first_t.translate('en')
                        else:
                            t = first_t
                if t:
                    raw_cues = t.fetch().to_raw_data()
                else:
                    raise RuntimeError("No suitable transcript found for this video.")
            except Exception as e:
                raise RuntimeError(f"Could not retrieve transcript for video {video_id}: {str(e)}")

        # Convert to TranscriptCue models
        cues: List[TranscriptCue] = []
        for item in raw_cues:
            text = item.get("text", "").replace("\n", " ").strip()
            if text:
                cues.append(TranscriptCue(
                    start=float(item.get("start", 0.0)),
                    duration=float(item.get("duration", 0.0)),
                    text=text
                ))

        if not cues:
            raise RuntimeError("Retrieved transcript is empty.")

        return cues

transcript_service = TranscriptService()
